version: '3.8'

services:
  data-analyst-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - TEMP_DIR=/tmp/analysis_temp
    volumes:
      - ./temp_data:/tmp/analysis_temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s